# Generated by Django 4.1.2 on 2023-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eloc', models.CharField(max_length=50)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
