# Generated by Django 4.1.2 on 2023-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_cat', models.CharField(max_length=100)),
                ('product_subcat', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='blog/image')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='eloc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=100),
        ),
    ]
