# Generated by Django 4.1.2 on 2023-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0002_book_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_ground',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
